name: Check CLA

permissions:
  contents: read

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  cla:
    name: Check CLA
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      statuses: write
      issues: write
    steps:
      - name: CLA Assistant
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: secondlife-3p/contributor-assistant@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.SHARED_CLA_TOKEN }}
        with:
          branch: master
          path-to-document: https://github.com/secondlife/cla/blob/main/CLA.md
          path-to-signatures: signatures.json
          remote-organization-name: ${{ secrets.SHARED_CLA_TOKEN && 'secondlife' || '' }}
          remote-repository-name: ${{ secrets.SHARED_CLA_TOKEN && 'cla-signatures' || '' }}
          allowlist: callum@mbp.localdomain,rye@lindenlab.com,jules-agent,jules@example.com,google-labs-jules[bot],google-labs-stitch[bot],*bot*,Kaleaon

