name: Manually Sign Windows Binaries

on:
  workflow_dispatch:
    inputs:
        build_run_number:
          description: 'GitHub Run Number (per build_viewer.yml workflow)'
          required: true
        # policy:
        #     description: 'Policy to sign binaries'
        #     required: true
        #     type: choice
        #     default: "Test"
        #     options:
        #     - "Test"
        #     - "Release"
        # viewer_version:
        #   description: 'viewer version not including build'
        #   required: true
        #   default: '7.1.10'
        # viewer_build:
        #   description: 'build id'
        #   required: true
        #   default: '799999'
        # viewer_release_type:
        #   description: 'release type'
        #   required: true
        #   default: 'Release'
        # branch:
        #   description: 'Branch to deploy from'
        #   required: false
        #   default: 'master'

permissions:
  contents: read

jobs:
  find-setup-files:
    runs-on: windows-latest
    permissions:
        actions: read
        contents: read
    outputs:
        setup_files: ${{ steps.get-files.outputs.setup_files }}
    steps:        
      - name: Download Build Artifacts
        uses: dawidd6/action-download-artifact@v11
        id: download
        with:
            workflow: build_viewer.yml
            run_number: ${{ github.event.inputs.build_run_number  }}
            name: .*windows.*
            name_is_regexp: true
            path: artifacts
      - name: Get List of Setup.exe Files
        id: get-files
        run: python ./fsutils/sign_utils.py get_setup_files
      - name: Upload Setup.exe Files
        uses: actions/upload-artifact@v4
        with:
          name: setup-exe-files
          path: setup_exe_files/
  sign-and-upload:
    name: Sign and Upload each Setup.exe
    needs: find-setup-files
    runs-on: windows-latest
    strategy:
      matrix:
        file: ${{ fromJson( needs.find-setup-files.outputs.setup_files) }}
    permissions:
        actions: read
        contents: read
    steps:
      - name: List Available Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: python ./fsutils/sign_utils.py list_run_artifacts
      
      - name: Download Setup.exe Files Artifact
        uses: actions/download-artifact@v5
        with:
          name: setup-exe-files
          path: setup_exe_files
      - name: Prepare File for Signing
        env:
          FILENAME: ${{ matrix.file }}
        run: python ./fsutils/sign_utils.py prepare_file
      # - name: Upload unsigned artifact
      #   id: upload-unsigned-artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: unsigned-artifact-${{ matrix.file }}
      #     path: to_sign/${{ matrix.file }}          

      # - name: sign the file
        # uses: signpath/github-action-submit-signing-request@v1
        # env:
        #     SIGNPATH_SIGNING_POLICY_SLUG: ${{ github.event.inputs.policy == 'Test' && vars.SIGNPATH_SIGNING_POLICY_SLUG_TEST || vars.SIGNPATH_SIGNING_POLICY_SLUG_RELEASE }}
        # with:
        #   api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
        #   organization-id: '${{ vars.SIGNPATH_ORGANIZATION_ID }}'
        #   project-slug: '${{ vars.SIGNPATH_PROJECT_SLUG }}'
        #   signing-policy-slug:  '${{ env.SIGNPATH_SIGNING_POLICY_SLUG }}'
        #   github-artifact-id:  "${{steps.upload-unsigned-artifact.outputs.artifact-id}}"
        #   wait-for-completion: true
        #   output-artifact-directory: 'application-signed'
      - name: Azure Trusted Signing
        uses: azure/trusted-signing-action@v0.5.9
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          endpoint: ${{ secrets.AZURE_ENDPOINT }}
          trusted-signing-account-name: ${{ secrets.AZURE_CODE_SIGNING_NAME }}
          certificate-profile-name: ${{ secrets.AZURE_CERT_PROFILE_NAME }}
        
          # Sign all exes inside the folder
          files-folder: ${{ github.workspace }}\to_sign
          files-folder-filter: exe
          
      # - name: Upload signed artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: signed-artifact-${{ matrix.file }}
      #     path: ./application-signed
            # - name: Upload unsigned artifact
      - name: Upload signed artifact
        id: upload-unsigned-artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-artifact-${{ matrix.file }}
          path: to_sign\${{ matrix.file }}          
