name: Tag FS Build

on:
  workflow_run:
    workflows: ["Build Viewer"]  # Exact name of the build workflow
    types:
      - completed
  workflow_dispatch:
    inputs:
      build_run_number:
        description: 'GitHub Run Number (per build_viewer.yml workflow)'
        required: true
      release_type:
        description: "Type of build"
        required: false
        type: choice
        default: "undefined"
        options:
          - "undefined"
          - "Manual"
          - "Nightly"
          - "Beta"
          - "Alpha"
          - "Release"
      viewer_version:
        description: 'Viewer version'
        required: false
        default: "undefined"
      viewer_build:
        description: 'Viewer build number'
        required: false
        default: "undefined"
      dry_run:
        description: 'Execute as dry run (no tag will be created)'
        required: false
        default: 'true'

permissions:
  contents: read

jobs:
  tag-build:
    permissions:
      contents: write
    # Run the job only if:
    # - The event is workflow_run **and** the conclusion is success
    # OR
    # - The event is workflow_dispatch (manual trigger)
    if: ${{ ( github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' ) || ( github.event_name == 'workflow_dispatch' ) }}
    runs-on: ubuntu-latest

    steps:
      # Checkout the Repository
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Necessary to fetch all history for tagging

      - name: Get Run Number
        id: get_run_number
        env:
          EVENT_NAME: ${{ github.event_name }}
          WORKFLOW_RUN_NUMBER: ${{ github.event.workflow_run.run_number }}
          INPUT_BUILD_RUN_NUMBER: ${{ github.event.inputs.build_run_number }}
        run: python ./fsutils/parse_workflow_inputs.py run_number

      - name: Download Build Artifacts
        uses: dawidd6/action-download-artifact@v11
        id: download_build_info
        with:
          workflow: build_viewer.yml
          run_number: ${{ steps.get_run_number.outputs.build_run_number }}
          name: build_info-${{ steps.get_run_number.outputs.build_run_number }}
          skip_unpack: false
          path: build_info

      # workout the inputs based on the trigger type
      - name: Query build info and parse workflow inputs
        id: get_inputs
        env:
          EVENT_NAME: ${{ github.event_name }}
          INPUT_RELEASE_TYPE: ${{ github.event.inputs.release_type }}
          INPUT_VIEWER_VERSION: ${{ github.event.inputs.viewer_version }}
          INPUT_VIEWER_BUILD: ${{ github.event.inputs.viewer_build }}
          INPUT_DRY_RUN: ${{ github.event.inputs.dry_run }}
          BUILD_INFO_FILE: build_info/build_info.json
        run: python ./fsutils/parse_workflow_inputs.py tag

      # Check if Tag Already Exists
      - name: Determine tag
        id: get_tag
        env:
          TAG_NAME: ${{ steps.get_inputs.outputs.tag_name }}
        run: python ./fsutils/manage_tags.py determine

      - name: Check if tag exists
        id: check_tag
        env:
          TAG_NAME: ${{ steps.get_tag.outputs.tag_name }}
        run: python ./fsutils/manage_tags.py check

      # Create the Tag (Conditional)
      - name: Create tag
        if: >
          steps.get_inputs.outputs.release_type != 'Nightly' &&
          steps.get_inputs.outputs.release_type != 'Manual' &&
          steps.get_inputs.outputs.release_type != 'Profiling' &&
          steps.get_inputs.outputs.dry_run != 'true' &&
          steps.check_tag.outputs.tag_exists == 'false'
        env:
          TAG_NAME: ${{ steps.get_tag.outputs.tag_name }}
          DRY_RUN: ${{ steps.get_inputs.outputs.dry_run }}
        run: python ./fsutils/manage_tags.py create

      # Push the Tag to the Repository (Conditional)
      - name: Push tag
        if: >
          steps.get_inputs.outputs.dry_run != 'true' &&
          steps.check_tag.outputs.tag_exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ steps.get_tag.outputs.tag_name }}
          DRY_RUN: ${{ steps.get_inputs.outputs.dry_run }}
        run: python ./fsutils/manage_tags.py push

      # Tagging Confirmation
      - name: Tagging Confirmation
        env:
          DRY_RUN: ${{ steps.get_inputs.outputs.dry_run }}
          TAG_EXISTS: ${{ steps.check_tag.outputs.tag_exists }}
          TAG_NAME: ${{ steps.get_tag.outputs.tag_name }}
        run: python ./fsutils/manage_tags.py confirm
