name: Tag a Build

permissions:
  contents: read

on:
  # schedule event triggers always run on the default branch
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    # run "nightly" builds on default branch every mon/wed/fri
    - cron: "21 2 * * 2,4,6"     # 2:21am UTC tues/thurs/sat == 7:21pm PDT mon/wed/fri -- see https://crontab.guru/#21_01_*_*_2,4,6
  workflow_dispatch:
    inputs:
      channel:
        description: "Channel to configure the build"
        required: true
        type: choice
        default: "Test"
        options:
        - "Test"
        - "Develop"
        - "Project"
        - "Release"
      project:
        description: "Project Name (used for channel name in project builds, and tag name for all builds)"
        default: "hippo"
      # TODO - add an input for selecting another sha to build other than head of branch

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Env Vars
        env:
          INPUT_CHANNEL: ${{ inputs.channel }}
          INPUT_PROJECT: ${{ inputs.project }}
          GITHUB_SHA: ${{ github.sha }}
        run: python ./fsutils/parse_workflow_inputs.py tag
      - name: Update Tag
        env:
          LL_TAG_RELEASE_TOKEN: ${{ secrets.LL_TAG_RELEASE_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          COMMIT_SHA: ${{ github.sha }}
        run: python ./fsutils/tag_release.py
